version: '3.8'

services:
  helpdesk-service:
    image: brunoah/hesk:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    ports:
      - target: 80
        published: 5544
        protocol: tcp
        mode: ingress
    volumes:
      - app-data:/var/www/html  # Maps the volume to /var/www/html in the container
    networks:
      - helpdesk-network

networks:
  helpdesk-network:
    external: true
    driver: overlay

volumes:
  app-data:

