version: '3.8'

services:
  helpdesk:
    image: helpdesk:3.5.1 # Use the image from your local registry
    deploy:
      replicas: 5 # Number of replicas
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      placement:
        constraints:
#          - node.role == worker
          - node.role == manager
    ports:
      - target: 80
        published: 5544
        protocol: tcp
        mode: ingress
    volumes:
      - /mnt/nfs/shared/helpdesk/app:/var/www/html
    environment:
      - PHP_MEMORY_LIMIT=256M
    networks:
      - helpdesk-network
networks:
  helpdesk-network:
    external: true
    driver: overlay