version: '3.8'
services:
  helpdesk:
    image: dregistrygui.uskoinc.com/helpdesk-image:3.5.1
    build:
      context: .
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: '1'
          memory: 1024M
      restart_policy:
        condition: on-failure
#    volumes:
#      - app-storage:/var/www/html  # Single volume for all necessary folders
    env_file:
      - .env
    expose:
      - 9000
    networks:
      - helpdesk-network
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
        mode: ingress
networks:
  helpdesk-network:
    external: true
    driver: overlay
#volumes:
#  app-storage:
#    driver: local
