version: "3.8"

services:
  hesk:
    image: dregistrygui.uskoinc.com/helpdesk:3.5.1
    deploy:
      replicas: 4
#      placement:
#        constraints:
#          - node.labels.role == master
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
    networks:
      - hesk-net
    volumes:
      - /mnt/nfs/shared/helpdesk/app:/var/www/html:rw
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "5545:80" # Host port : container port
    restart: always

networks:
  hesk-net:
    external: true