version: '3.8'
services:
  helpdesk:
    image: helpdesk-image
    build:
      context: .
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: '1'
          memory: 1024M
      restart_policy:
        condition: on-failure
    volumes:
      - app-storage:/var/www/html  # Single volume for all necessary folders
    env_file:
      - .env
    networks:
      - helpdesk-network
    ports:
      - "8089:80"  # Port for accessing the PHP application
networks:
  helpdesk-network:
    driver: overlay
volumes:
  app-storage:
    driver: local
