version: '3.8'

services:
  helpdesk:
    image: helpdesk:latest # Use the image from your local registry
    deploy:
      replicas: 5 # Number of replicas
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      placement:
        constraints:
#          - node.role == worker
          - node.role == manager
    ports:
      - target: 80
        published: 5544
        protocol: tcp
        mode: ingress
    volumes:
#      - nfs:/var/www/html
      - /mnt/nfs/shared/helpdesk:/var/www/html
    environment:
      - PHP_MEMORY_LIMIT=256M
    networks:
      - helpdesk-network
#volumes:
#  nfs:

#    driver: local
#    driver_opts:
#      type: nfs
#      o: addr=192.168.24.193,rw
##      device: ":/mnt/nfs/shared/helpdesk"
#      device: ":/srv/nfs/shared/helpdesk"
networks:
  helpdesk-network:
    external: true
    driver: overlay